# Generated by Django 4.2.30 on 2026-07-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='billing_day',
            field=models.PositiveIntegerField(default=1, help_text='Day of the month when the bill closes.'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='due_day',
            field=models.PositiveIntegerField(default=10, help_text='Day of the month when the bill is due.'),
        ),
    ]
